---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_token: 31ceb090a5a818a830f95622c3c2b5e8574010f0c16c0350d6a5cf3d8de0cfb7
    ansible_user_id: parallels
    digitalocean_api_token: bf8ae6891e555f7c1088e8f2f2beee24dbf3dd68c46460f3976598c18db3c68b

  tasks:
    - name: Ensure ssh key exists.
      user: 
        name: "{{ ansible_user_id }}"
        generate_ssh_key: yes
        ssh_key_file: .ssh/id_rsa
      register: ssh_key
 
#    - name: Display information about local key.
#      debug:
#        msg: "Key is {{ ssh_key }}"

    - name: Ensure key exists at DigitalOcean.
      digital_ocean:
        state: present
        command: ssh
        name: ansible
        ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        api_token: "{{ ansible_token }}"
      register: ansible_key

#    - name: Display information about key.
#      debug:
#        msg: "Key is {{ ansible_key }}"

    - name: Create new droplet.
      digital_ocean:
        state: present
        command: droplet
        name: ansibletest
        api_token: "{{ digitalocean_api_token }}"
        region_id: nyc3
        image_id: ubuntu-16-04-x64
        ssh_key_ids: "{{ ansible_key.ssh_key.id }}"
        size_id: 2gb
        wait_timeout: 500
        unique_name: yes
      register: dropletoutput

    - name: Display information about droplet.
      debug:
        msg: "ID is {{ dropletoutput.droplet.id }}"

    - name: Display information about droplet.
      debug:
        msg: "IP address is {{ dropletoutput.droplet.ip_address }}"

    - name: add jumpbox to in-memory inventory
      add_host:
        hostname: 'jumpbox'
        ansible_host: "{{ dropletoutput.droplet.ip_address }}"


